In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')

df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam'] = df.Category.apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['spam'],test_size=0.2)

In [6]:
X_train.shape

(4457,)

In [7]:
type(y_train)

pandas.core.series.Series

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)

X_train_cv

<4457x7702 sparse matrix of type '<class 'numpy.int64'>'
	with 59161 stored elements in Compressed Sparse Row format>

In [10]:
X_train_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [11]:
X_train_cv.shape

(4457, 7702)

In [12]:
v.vocabulary_

{'hello': 3388,
 'my': 4650,
 'love': 4214,
 'how': 3504,
 'goes': 3155,
 'that': 6778,
 'day': 2158,
 'wish': 7504,
 'your': 7669,
 'well': 7418,
 'and': 953,
 'fine': 2840,
 'babe': 1180,
 'hope': 3478,
 'you': 7664,
 'find': 2837,
 'some': 6270,
 'job': 3823,
 'prospects': 5457,
 'miss': 4489,
 'boytoy': 1461,
 'teasing': 6713,
 'kiss': 3942,
 'much': 4617,
 'it': 3749,
 'will': 7483,
 'cost': 1994,
 'approx': 1028,
 'per': 5131,
 'month': 4560,
 'then': 6795,
 'ur': 7156,
 'physics': 5183,
 'get': 3105,
 'nah': 4665,
 'man': 4321,
 'car': 1628,
 'is': 3738,
 'meant': 4398,
 'to': 6903,
 'be': 1265,
 'crammed': 2029,
 'full': 3028,
 'of': 4878,
 'people': 5129,
 'glad': 3135,
 'didn': 2277,
 'totally': 6963,
 'disagreeable': 2316,
 'lol': 4175,
 'home': 3462,
 'under': 7106,
 'the': 6781,
 'sea': 5945,
 'there': 6801,
 'lays': 4033,
 'rock': 5791,
 'in': 3626,
 'an': 948,
 'envelope': 2600,
 'paper': 5063,
 'on': 4923,
 'are': 1042,
 'words': 7553,
 'what': 7439,
 'up': 7139,
 'bruv

In [13]:
X_train_np = X_train_cv.toarray()

In [28]:
np.where(X_train_np[0]>1)[0]

array([ 953, 6778, 7664])

In [29]:
X_train_np[0][953]

2

In [31]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
model = MultinomialNB()

model.fit(X_train_cv,y_train)

MultinomialNB()

In [32]:
X_test_cv = v.transform(X_test)
y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       973
           1       0.95      0.92      0.93       142

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



# now test from outside of dataset

In [33]:
emails = [
    'Hey, mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [35]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [37]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       973
           1       0.95      0.92      0.93       142

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

